weights: yolo/yolov5s.pt
cfg: models/yolov5s.yaml
data: "E:/ylxy/data/\u65B0\u5EFA\u6587\u4EF6\u5939/data.yaml"
hyp: data/hyps/hyp.scratch.yaml
epochs: 3
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: "E:/\u684C\u9762/yolov5-gui/yolov5-master/yolo/train"
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: "E:\\\u684C\u9762\\yolov5-gui\\yolov5-master\\yolo\\train\\exp"
